name: BungeeCordLinkersPortal
version: @version@
softdepend: [Multiverse-Core]
main: world.ddpn.bungeecordlinkersportal.BungeeCordLinkersPortal
authors: [ddPn08]
commands:
  LinkersPortal:
    permission: BungeeCordLinkersPortal.command.use
