name: BungeeCordLinkersPortal
version: @version@
main: world.ddpn.bungeecordlinkersportal.BungeeCordLinkersPortal
api-version: 1.16
authors: [ddPn08]
commands:
  LinkersPortal:
    aliases: ["LPortal","LinkersPortal"]
